### sklearn.preprocessing.LabelEncoder
* fit -> transform

In [8]:
from sklearn.preprocessing import LabelEncoder

items=['TV', '냉장고', '전자렌지', '컴퓨터' ,'선풍기' '선풍기', '믹서', '믹서']

# LabelEncoder를 객체로 생성한 후, fit() 과 transform()으로 label 인코딩 수행.

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)




인코딩 변환값: [0 1 4 5 3 2 2]


In [9]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기선풍기' '전자렌지' '컴퓨터']


In [11]:
print('디코딩 원본 값:' , encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기선풍기' '선풍기선풍기']


### sklearn.preprocessing.OneHotEncoder

In [15]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items=['TV', '냉장고', '전자렌지', '컴퓨터' ,'선풍기' '선풍기', '믹서', '믹서']

# 먼저 숫자값으로 변환을 위해 LableEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 2차원 데이터로 변환
labels=labels.reshape(-1,1)

#원- 한 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)


원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(7, 6)


In [16]:
# 판다스에서 지원하는 원-핫 인코딩 get_dummies()
import pandas as pd 
df=pd.DataFrame({'item':['TV', '냉장고', '전자렌지', '컴퓨터' ,'선풍기' '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기선풍기  item_전자렌지  item_컴퓨터
0        1         0        0            0          0         0
1        0         1        0            0          0         0
2        0         0        0            0          1         0
3        0         0        0            0          0         1
4        0         0        0            1          0         0
5        0         0        1            0          0         0
6        0         0        1            0          0         0